### ISSUE TITLE
Error while loading shared libraries at runtime

### ISSUE THREAD

**Issue by iKenWoo** [kylef/heroku-buildpack-swift#7]
I'm running into an issue when trying to deploy a [zewo](https://github.com/Zewo/Zewo) server. 

The app compiles correctly, but when the process tries to start the binary, it crashes with: `error while loading shared libraries: libCLibvenice.so: cannot open shared object file: No such file or directory`.

If I check the heroku server, I see the .so library in `/app/.swift-bin` folder so I'm not sure why the binary can't find it. 

Any ideas?

**Comment by iKenWoo** [comment]
Added a pull request to fix this.

**Comment by funkenstrahlen** [comment]
I just stumbled on this issue because I have a similar problem.

My `.swift-lib` folder contains `libFoundation.so  libXCTest.so	libdispatch.so	libswiftCore.so  libswiftGlibc.so  libswiftRemoteMirror.so  libswiftSwiftOnoneSupport.so`

When I try to run my code I get this error: `./binary: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory`

I am stuck trying to fix this, because in contrast to @ikenwoo my library is actually missing.
